---
title: "Data viz"
author: "Sabina SH Andersen"
date: "17/6/2021"
output: html_document
---

```{r setup}
# load packages

source(here::here("R/package-loading.R"))

# load the tidied dataset 

load(here::here("data/nhanes_small.rda"))
```

# One variable plots

```{r continuous-variables}
ggplot(nhanes_small, aes(x = bmi)) +
    geom_density()

ggplot(nhanes_small, aes(x = bmi)) + 
    geom_histogram()

```

```{r discrete-variables}

ggplot(nhanes_small, aes(x = gender)) +
    geom_bar()

ggplot(nhanes_small, aes(x = diabetes)) +
    geom_bar()

#Does not remove the entire row

nhanes_small %>% 
    drop_na(diabetes) %>% 
    ggplot(aes(x = diabetes)) + geom_bar()

```

```{r remove-missing-diabetes}

#removes the entire case - remember that

nhanes_tidied <- nhanes_small %>% 
    filter(!is.na(diabetes))

# save data

usethis::use_data(nhanes_tidied, overwrite = T)

# Now make plot with out diabetes 

ggplot(nhanes_tidied, aes(x = diabetes)) +
    geom_bar()
```

#plotting two varibles

```{r 2-continous-variables}

# ved at definere som nedenstående behøver man ikke at skrive hele koden hver gang.  

bmi_chol <- ggplot(nhanes_tidied, aes(x = bmi, y = tot_chol))

bmi_chol + geom_point()

bmi_chol + geom_hex()

bmi_chol + geom_smooth()

bmi_chol + geom_hex() + geom_smooth()

```

```{r 2-discrete-variables}

# ved at definere som nedenstående behøver man ikke at skrive hele koden hver gang.

two_discrete <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, fill = gender))

two_discrete + geom_bar()

two_discrete + geom_bar(position = position_dodge())

```

```{r discrete-continuous-variables}

two_mixed <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, y = bmi))

two_mixed + geom_boxplot()

two_mixed + geom_jitter()

two_mixed + geom_violin()

```

# Exercise to make plots with one or two variables (11.5)

```{r}

# 1a. Distribution of age

ggplot(nhanes_tidied, aes(x = age)) +
    geom_histogram()
    
# 1b. Distribution of age of diabetes diagnosis

ggplot(nhanes_tidied, aes(x = diabetes_age)) +
    geom_histogram()

# 2a. Number of people who smoke now

ggplot(nhanes_small, aes(x = smoke_now)) +
    geom_bar()

# 2b. Number of people who are physically active

ggplot(nhanes_small, aes(x = phys_active )) +
    geom_bar()

# 3a. BMI in relation to systolic blood pressure
ggplot(nhanes_small, aes(x = bmi, y = bp_sys_ave)) +
    geom_hex()

# 3b. BMI relation to diastolic blood pressure
ggplot(nhanes_small, aes(x = bmi, y = bp_dia_ave)) +
    geom_hex()
    
# 4. Physically active people with or without diabetes
ggplot(nhanes_small, aes(x = diabetes, fill = phys_active)) +
    geom_bar(position = position_dodge())

# 5. Poverty levels between those with or without diabetes
ggplot(nhanes_small, aes(x = diabetes, y = poverty)) + geom_violin()
```


# plotting three or more variables

```{r using-colour}

# 1 continuous and 2 discrete varibles

nhanes_tidied %>% 
    ggplot(aes(x = gender, y = bp_sys_ave, colour = diabetes)) + geom_boxplot()

# 3 continuous variables

nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = age)) + geom_point()

# 2 continuous and 1 discrete variable

nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = diabetes)) + geom_point()

```

```{r using-faceting}

# side-by-side
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave)) +
    geom_point()+
    facet_grid(cols = vars(diabetes))

# stacked

nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave)) +
    geom_point()+
    facet_grid(rows = vars(diabetes))

# 5 variables

nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = age)) +
    geom_point() +
    facet_grid(rows = vars(diabetes), cols = vars(gender))

```

#changing colour

```{r exercise-colour}

base_barplot <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, fill = gender)) +
    geom_bar(position = position_dodge())

base_barplot

base_barplot + 
    scale_fill_viridis_d()

base_barplot + 
    scale_fill_viridis_d(option = "E")


base_scatterplot <- nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = age)) +
    geom_point()

base_scatterplot + 
    scale_colour_viridis_c() 

base_scatterplot + 
    scale_colour_viridis_c(option = "M")

```

# changing plot appearance
```{r built-in-themes}

# Create scatterplot to play with themes
base_scatterplot2 <- base_scatterplot +
    facet_grid(rows = vars(diabetes),
               cols = vars(gender)) +
    scale_color_viridis_c()

# View the plot with the default theme
base_scatterplot2

#Try different theme
base_scatterplot2 + 
    theme_bw()

base_scatterplot2 + 
    theme_minimal()

base_scatterplot2 + 
    theme_classic()

# set the theme for all plots
theme_set(theme_bw())

#change title and labels

base_scatterplot2 + 
    labs(title = "BMI, systolic blood pressure, and age, by diabetes and gender", y = "Systolic blood pressure (mmHg)", x = "BMI (kg/m2")

```

# Saving the plot

```{r}
ggsave(here::here("doc/images/scatterplot.pdf"),
      base_scatterplot2, width = 7, height = 5)
```

